import Link from "next/link";
import { SHOWCASE_EXAMPLES } from "@/lib/showcase-examples";

export const metadata = {
  title: "Templates — Magic AI",
  description:
    "Browse real sites generated by Magic AI — coffee shops, portfolios, SaaS, hotels, and more.",
};

export default function TemplatesPage() {
  return (
    <main className="min-h-screen bg-atmosphere">
      <header className="mx-auto flex max-w-6xl items-center justify-between px-6 py-6">
        <Link href="/" className="font-[family-name:var(--font-brand)] text-2xl italic text-fog">
          magic ai
        </Link>
        <Link
          href="/signup"
          className="rounded-full bg-lime px-5 py-2 text-sm font-semibold text-ink"
        >
          Start free
        </Link>
      </header>

      <div className="mx-auto max-w-6xl px-6 pb-24 pt-8">
        <h1 className="font-[family-name:var(--font-display)] text-4xl font-bold sm:text-5xl">
          Template gallery
        </h1>
        <p className="mt-4 max-w-2xl text-mist">
          Each card started as a one-line brief. Click any example to preview the full
          site, or sign up and remix the prompt in the builder.
        </p>

        <div className="mt-14 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
          {SHOWCASE_EXAMPLES.map((ex) => (
            <Link
              key={ex.slug}
              href={`/examples/${ex.slug}`}
              target="_blank"
              className="group rounded-2xl border border-[var(--line)] bg-ink-soft/40 p-5 transition hover:border-lime/40"
            >
              <p className="text-xs uppercase tracking-wider text-lime">{ex.category}</p>
              <h2 className="mt-2 font-[family-name:var(--font-display)] text-xl font-bold group-hover:text-lime">
                {ex.title}
              </h2>
              <p className="mt-2 line-clamp-2 text-sm text-mist">{ex.prompt}</p>
              <p className="mt-4 text-xs text-mist">UI kit: {ex.uiKit}</p>
            </Link>
          ))}
        </div>
      </div>
    </main>
  );
}
