import type { IndustryTemplate } from "./types";

/**
 * Curated industry blueprints. Section ids must exist in SECTION_REGISTRY.
 * Design tokens are layered onto theme presets at generate time.
 */
export const INDUSTRY_TEMPLATES: IndustryTemplate[] = [
  {
    id: "restaurant",
    industry: "restaurant",
    keywords: [
      "restaurant",
      "cafe",
      "coffee",
      "bistro",
      "dining",
      "menu",
      "chef",
      "cuisine",
      "eatery",
      "bar",
      "wine",
      "brunch",
    ],
    style: "Warm hospitality with appetite-led imagery and clear reservation CTA",
    theme: "warm_editorial",
    design: {
      accent: "#B45309",
      buttonBg: "#B45309",
      buttonText: "#FFFBEB",
      surface: "#FFFBF5",
      surfaceAlt: "#F5EDE3",
      text: "#292524",
      muted: "#78716C",
      displayFont: "Playfair Display",
      bodyFont: "DM Sans",
      radius: "small",
    },
    sections: [
      "hero_split",
      "features_3col",
      "about_text",
      "testimonial_single",
      "cta_band",
      "contact_form",
      "footer_simple",
    ],
    toneRules: [
      "Lead with dish names, neighbourhood, and dining occasion",
      "Sound inviting, never corporate",
      "CTA should be Reserve, Book a table, or Order",
    ],
    dontRules: [
      "No SaaS pricing tiers",
      "No generic 'welcome to our website'",
      "Avoid stocky 'fine dining experience' filler",
    ],
    headlinePatterns: [
      "{cuisine} in {city}",
      "Tables for {occasion}",
      "From the kitchen of {brand}",
    ],
    layoutRules: [
      "Hero with food or dining room image",
      "Features as signature dishes or service moments",
      "Contact near the end for reservations",
    ],
  },
  {
    id: "bakery",
    industry: "bakery",
    keywords: [
      "bakery",
      "baker",
      "sourdough",
      "pastry",
      "pastries",
      "bread",
      "cake",
      "patisserie",
      "croissant",
      "loaf",
      "wholesale",
    ],
    style: "Rustic artisan warmth with product-forward hero",
    theme: "warm_editorial",
    design: {
      accent: "#9A3412",
      buttonBg: "#9A3412",
      buttonText: "#FFF7ED",
      surface: "#FFF7ED",
      surfaceAlt: "#FFEDD5",
      text: "#431407",
      muted: "#9A3412",
      displayFont: "Instrument Serif",
      bodyFont: "DM Sans",
      radius: "medium",
    },
    sections: [
      "hero_split",
      "features_3col",
      "feature_image_left",
      "about_text",
      "faq_accordion",
      "contact_form",
      "footer_simple",
    ],
    toneRules: [
      "Name real products (sourdough, pastries, wholesale)",
      "Mention pickup, hours, or wholesale when in the brief",
      "Keep copy short and sensory",
    ],
    dontRules: [
      "No tech/startup jargon",
      "No pricing_3tier unless the brief asks for plans",
      "Avoid purple or neon accents",
    ],
    headlinePatterns: [
      "{product} baked in {city}",
      "Loaves, pastries, and {offer}",
      "Fresh from {brand}",
    ],
    layoutRules: [
      "Hero image of bread or pastry",
      "Features as product lines",
      "FAQ for hours, orders, wholesale",
    ],
  },
  {
    id: "saas",
    industry: "saas",
    keywords: [
      "saas",
      "software",
      "platform",
      "app",
      "startup",
      "subscription",
      "dashboard",
      "api",
      "b2b",
      "product",
      "tool",
      "automation",
    ],
    style: "Clean product marketing with proof and pricing",
    theme: "bold_startup",
    design: {
      accent: "#0F766E",
      buttonBg: "#0F766E",
      buttonText: "#ECFDF5",
      primary: "#0F172A",
      surface: "#FFFFFF",
      surfaceAlt: "#F8FAFC",
      text: "#0F172A",
      muted: "#64748B",
      displayFont: "Space Grotesk",
      bodyFont: "Inter",
      radius: "medium",
    },
    sections: [
      "hero_split",
      "logos_strip",
      "features_3col",
      "pricing_3tier",
      "testimonial_single",
      "faq_accordion",
      "cta_band",
      "footer_simple",
    ],
    toneRules: [
      "Lead with the job-to-be-done, not company history",
      "Pricing copy must be concrete (plan names + price)",
      "Keep CTAs action-oriented: Start free, Book demo",
    ],
    dontRules: [
      "No restaurant/menu language",
      "Avoid vague 'transform your business'",
      "Do not invent fake enterprise logos as brands from the brief",
    ],
    headlinePatterns: [
      "{outcome} without the busywork",
      "The {category} platform for {audience}",
      "Ship {benefit} in days, not months",
    ],
    layoutRules: [
      "Hero + logos for trust",
      "Pricing before FAQ",
      "Close with a single strong CTA band",
    ],
  },
  {
    id: "portfolio",
    industry: "portfolio",
    keywords: [
      "portfolio",
      "designer",
      "photographer",
      "creative",
      "freelancer",
      "illustrator",
      "artist",
      "work",
      "showcase",
      "studio",
    ],
    style: "Editorial portfolio with work-first hierarchy",
    theme: "minimal_studio",
    design: {
      accent: "#D4A373",
      buttonBg: "#E8E8EA",
      buttonText: "#111214",
      surface: "#111214",
      surfaceAlt: "#1A1B1F",
      text: "#E8E8EA",
      muted: "#9CA3AF",
      displayFont: "Manrope",
      bodyFont: "Manrope",
      radius: "none",
    },
    sections: [
      "hero_centered",
      "feature_image_left",
      "feature_image_right",
      "about_text",
      "testimonial_single",
      "contact_form",
      "footer_simple",
    ],
    toneRules: [
      "Name the medium and specialty early",
      "Sound personal and specific, not agency-corporate",
      "CTA should invite collaboration or booking",
    ],
    dontRules: [
      "No pricing tables unless asked",
      "No fake client logo strips",
      "Avoid overcrowding the hero with stats",
    ],
    headlinePatterns: [
      "{specialty} for {audience}",
      "Selected work by {brand}",
      "{medium} with a point of view",
    ],
    layoutRules: [
      "Centered hero, then alternating image features",
      "About before contact",
      "Keep section count lean",
    ],
  },
  {
    id: "hotel",
    industry: "hotel",
    keywords: [
      "hotel",
      "boutique hotel",
      "inn",
      "resort",
      "lodge",
      "stay",
      "rooms",
      "hospitality",
      "guesthouse",
      "booking",
    ],
    style: "Quiet luxury hospitality with booking-forward CTAs",
    theme: "warm_editorial",
    design: {
      accent: "#1F4E46",
      buttonBg: "#1F4E46",
      buttonText: "#F4F7F6",
      surface: "#F7F4EF",
      surfaceAlt: "#EFE9E0",
      text: "#1C1917",
      muted: "#78716C",
      displayFont: "Playfair Display",
      bodyFont: "Inter",
      radius: "small",
    },
    sections: [
      "hero_split",
      "features_3col",
      "feature_image_left",
      "about_text",
      "testimonial_single",
      "faq_accordion",
      "contact_form",
      "footer_simple",
    ],
    toneRules: [
      "Lead with place, rooms, and stay experience",
      "Mention location and booking clearly",
      "Tone is calm and specific, never salesy",
    ],
    dontRules: [
      "No SaaS pricing tiers",
      "No startup jargon",
      "Avoid generic 'luxury redefined' clichés",
    ],
    headlinePatterns: [
      "Stay in {city}",
      "Rooms with {amenity}",
      "{brand} — a quiet stay in {city}",
    ],
    layoutRules: [
      "Hero with property or room image",
      "Features as amenities",
      "FAQ for check-in, parking, pets",
    ],
  },
  {
    id: "dental",
    industry: "dental",
    keywords: [
      "dental",
      "dentist",
      "orthodont",
      "teeth",
      "smile",
      "clinic",
      "oral",
      "hygiene",
      "invisalign",
      "braces",
    ],
    style: "Clean clinical trust with appointment CTA",
    theme: "bold_startup",
    design: {
      accent: "#0284C7",
      buttonBg: "#0284C7",
      buttonText: "#F0F9FF",
      primary: "#0C4A6E",
      surface: "#FFFFFF",
      surfaceAlt: "#F0F9FF",
      text: "#0F172A",
      muted: "#64748B",
      displayFont: "Manrope",
      bodyFont: "Inter",
      radius: "large",
    },
    sections: [
      "hero_centered",
      "features_3col",
      "about_text",
      "testimonial_single",
      "faq_accordion",
      "cta_band",
      "contact_form",
      "footer_simple",
    ],
    toneRules: [
      "Reassure with services, hours, and insurance if mentioned",
      "CTAs: Book appointment, Request a visit",
      "Keep medical claims modest and specific",
    ],
    dontRules: [
      "No scare tactics",
      "No fake before/after medical claims",
      "Avoid dark neon aesthetics",
    ],
    headlinePatterns: [
      "Gentle dentistry in {city}",
      "Smiles, cleanings, and {service}",
      "Book your visit at {brand}",
    ],
    layoutRules: [
      "Centered hero for calm trust",
      "Services as three features",
      "Contact + CTA for booking",
    ],
  },
  {
    id: "agency",
    industry: "agency",
    keywords: [
      "agency",
      "marketing",
      "branding",
      "advertising",
      "creative agency",
      "digital agency",
      "campaigns",
      "clients",
      "strategy",
    ],
    style: "Confident agency site with proof and services",
    theme: "bold_startup",
    design: {
      accent: "#EA580C",
      buttonBg: "#111827",
      buttonText: "#F9FAFB",
      primary: "#111827",
      surface: "#FFFFFF",
      surfaceAlt: "#F3F4F6",
      text: "#111827",
      muted: "#6B7280",
      displayFont: "Archivo",
      bodyFont: "Inter",
      radius: "small",
    },
    sections: [
      "hero_split",
      "logos_strip",
      "features_3col",
      "feature_image_left",
      "testimonial_single",
      "cta_band",
      "contact_form",
      "footer_simple",
    ],
    toneRules: [
      "Lead with outcomes for clients, not internal process fluff",
      "Name service lines clearly",
      "CTA: Start a project, Talk to us",
    ],
    dontRules: [
      "No restaurant copy patterns",
      "Avoid empty buzzwords without a concrete offer",
      "Do not invent Fortune-500 clients",
    ],
    headlinePatterns: [
      "Brands that {outcome}",
      "{service} for ambitious teams",
      "Work that moves {metric}",
    ],
    layoutRules: [
      "Hero + logos strip early",
      "Services as features",
      "Case-style image feature before contact",
    ],
  },
  {
    id: "gym",
    industry: "gym",
    keywords: [
      "gym",
      "fitness",
      "workout",
      "training",
      "crossfit",
      "yoga",
      "pilates",
      "coach",
      "membership",
      "personal training",
    ],
    style: "Energetic membership site with clear plans",
    theme: "bold_startup",
    design: {
      accent: "#16A34A",
      buttonBg: "#16A34A",
      buttonText: "#F0FDF4",
      primary: "#14532D",
      surface: "#FFFFFF",
      surfaceAlt: "#F0FDF4",
      text: "#14532D",
      muted: "#4B5563",
      displayFont: "Space Grotesk",
      bodyFont: "Inter",
      radius: "medium",
    },
    sections: [
      "hero_split",
      "features_3col",
      "pricing_3tier",
      "testimonial_single",
      "faq_accordion",
      "cta_band",
      "footer_simple",
    ],
    toneRules: [
      "Lead with training style and membership clarity",
      "Pricing must feel real (Starter / Pro / Unlimited)",
      "Energetic but not shouty",
    ],
    dontRules: [
      "No medical or clinical tone",
      "Avoid generic 'unleash your potential' alone",
      "No dark purple glow aesthetics",
    ],
    headlinePatterns: [
      "Train at {brand}",
      "{city} strength and conditioning",
      "Memberships built for {audience}",
    ],
    layoutRules: [
      "Hero with gym or training image",
      "Pricing after features",
      "FAQ for hours and memberships",
    ],
  },
  {
    id: "boutique",
    industry: "boutique",
    keywords: [
      "boutique",
      "shop",
      "store",
      "retail",
      "florist",
      "flowers",
      "orchid",
      "apparel",
      "clothing",
      "gift",
      "handmade",
    ],
    style: "Product boutique with warm merchandising cues",
    theme: "warm_editorial",
    design: {
      accent: "#BE185D",
      buttonBg: "#BE185D",
      buttonText: "#FDF2F8",
      surface: "#FFF1F2",
      surfaceAlt: "#FFE4E6",
      text: "#1F2937",
      muted: "#6B7280",
      displayFont: "Instrument Serif",
      bodyFont: "DM Sans",
      radius: "medium",
    },
    sections: [
      "hero_split",
      "features_3col",
      "about_text",
      "testimonial_single",
      "faq_accordion",
      "contact_form",
      "footer_simple",
    ],
    toneRules: [
      "Lead with product category and neighbourhood",
      "Mention pickup, shipping, or shop hours when relevant",
      "Keep product language concrete",
    ],
    dontRules: [
      "No SaaS pricing ladders unless asked",
      "Avoid generic ecommerce buzzwords",
      "Do not invent inventory the brief never mentioned",
    ],
    headlinePatterns: [
      "{product} from {city}",
      "Shop {category} at {brand}",
      "Handmade {product} for {occasion}",
    ],
    layoutRules: [
      "Hero with product photography",
      "Features as product lines or services",
      "Contact for pickup / custom orders",
    ],
  },
];

export const TEMPLATE_BY_ID = Object.fromEntries(
  INDUSTRY_TEMPLATES.map((t) => [t.id, t]),
) as Record<string, IndustryTemplate>;
