/**
 * Expand seeds into the AI template registry module.
 *
 * Run: npm run templates:build
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { generateTemplateLibrary } from "../src/lib/templates/generate";
import { validateStructure } from "../src/lib/spec/validate";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(
  __dirname,
  "../src/lib/templates/library/registry.generated.ts",
);

function main() {
  const { templates, stats } = generateTemplateLibrary();

  let invalid = 0;
  for (const t of templates) {
    const err = validateStructure(t.sections);
    if (err) {
      invalid += 1;
      console.warn(`Invalid structure for ${t.id}: ${err}`);
    }
  }

  const header = `/**
 * AUTO-GENERATED by scripts/build-templates.ts — do not edit by hand.
 * Run: npm run templates:build
 *
 * Total: ${stats.total}
 * By category: ${JSON.stringify(stats.byCategory)}
 */

import type { AiTemplate } from "../types";

export const GENERATED_TEMPLATES: AiTemplate[] = `;

  const body = JSON.stringify(templates, null, 2);
  const footer = ` as AiTemplate[];

export const GENERATED_TEMPLATE_STATS = ${JSON.stringify(stats, null, 2)} as const;
`;

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, `${header}${body}${footer}\n`, "utf8");

  console.log(`Wrote ${templates.length} templates → ${outPath}`);
  console.log("By category:", stats.byCategory);
  if (invalid > 0) {
    console.error(`${invalid} templates failed structure validation`);
    process.exit(1);
  }
  if (templates.length < 280) {
    console.error(`Expected ≥280 templates, got ${templates.length}`);
    process.exit(1);
  }
}

main();
